allow_hosts:
- af.hilton.com
- af3.hilton.com
- alohaapac.hilton.com
- alohaemea.hilton.com
- asiapac.hilton.com
- aw.hilton.com
- brandmanagementsupport.hilton.com
- canopy.hilton.com
- canopy3.hilton.com
- chatan.hiltonjapan.co.jp

ssl_insecure: True