allow_hosts:
- biometric.citigym.com.vn
- sol.citigym.com.vn
- thankyou.citigym.com.vn
- lucky.citigym.com.vn
- news.citigym.com.vn
- pt4.citigym.com.vn
- dealsoc.citigym.com.vn
- bt5.citigym.com.vn
- deal.citigym.com.vn
- git11.citigym.com.vn
- datlich.citigym.com.vn
- ms.citigym.com.vn
- tm.citigym.com.vn
- promotion.citigym.com.vn
- tuyendung.citigym.com.vn
- trial.citigym.com.vn
- gi.citigym.com.vn
- fit.citigym.com.vn
- vongquay.citigym.com.vn
- mba.citigym.com.vn
- partners.citigym.com.vn
- gfp.citigym.com.vn
- bt4.citigym.com.vn
- rewards.citigym.com.vn
- giaoantapluyen.citigym.com.vn
- app.citigym.com.vn
- beta.citigym.com.vn
- pt.citigym.com.vn
- signature.citigym.com.vn
- kbyt.citigym.com.vn
- evoucher.citigym.com.vn
- dangky.citigym.com.vn
- hoaxuan.citigym.com.vn
- rpc.citigym.com.vn
- booking.citigym.com.vn
- hdsdnoibo.citigym.com.vn
- citigym.com.vn
- cskh.citigym.com.vn
- dragonpalace.citigym.com.vn
- uudai.citigym.com.vn
- event.citigym.com.vn
- pay.citigym.com.vn
- giamcan.citigym.com.vn
- terms.citigym.com.vn
- yoga.citigym.com.vn
- www.citigym.com.vn
- docs.citigym.com.vn
- ck.citigym.com.vn
- gcp.citigym.com.vn
- novaid.citigym.com.vn
- yep.citigym.com.vn
- vmbc.citigym.com.vn
- sieuthi0dong.citigym.com.vn


ssl_insecure: True