bug-type:
  sqli:
    attack-mode: "off"
    payload-mode: "cluster"
    target-parameters:
      - "category"
  xss:
    attack-mode: "off"
    payload-mode: "cluster"
    target-parameters:
      - "search"
      - "category"
  rce:
    attack-mode: "attack"
    payload-mode: "sniper"
    target-parameters:
      - "storeId"
